### PR TITLE
Add rainbow Textscreens

### PR DESCRIPTION
**Pull request by TomDotBat**
Adds a rainbow Textscreen feature, as mentioned in #67.

### CODE REVIEW

**Comment by Cherry** [comment]
This looks awesome, thanks for the contribution! I'll endeavor to test this shortly and get back to you.

I believe we'll also want to add this functionality to the perma text screen spawning at https://github.com/Cherry/3D2D-Textscreens/blob/e710df7b3df58bd569f0ec25a9b293b664b800f5/lua/autorun/textscreens_util.lua#L71?

**Comment by TomDotBat** [comment]
Ah yes, well spotted. I'll sort that out when I have a moment.

**Comment by Cherry** [comment]
Thanks! I believe it will also needed to be added to the command that saves them too: https://github.com/TomDotBat/3D2D-Textscreens/blob/b241a2b98bdbf53e5b1ac096442ddc0d506c9dcc/lua/autorun/textscreens_util.lua#L126

**Review by Cherry — APPROVED** [review]
Looks great, thanks very much. Merging and will release shortly.

**Pull request merged**
