### PR TITLE
Added a convar to restrict the number of characters per line

### PR DESCRIPTION
**Pull request by Seef0x**

### CODE REVIEW

**Comment by Cherry** [comment]
Thanks for the PR! This seems like a great idea. Could you update your branch to fix the [linting issues](https://github.com/Cherry/3D2D-Textscreens/actions/runs/3234571789/jobs/5298985179) please? I'll be happy to test and merge after that's done.

**Comment by Cherry** [comment]
Looks like there's still a few linting issues remaining, mainly over the use of `!=` vs `~=` as per the rest of the codebase. I'd recommend running `glualint` before committing to test this locally.

**Comment by Seef0x** [comment]
@Cherry its done 👍

**Review by Cherry — APPROVED** [review]

**Comment by Cherry** [comment]
Thanks, sorry for the delay. Merging and releasing today.

**Pull request merged**
